#!/usr/bin/env bash

reset() {
	pushd .. >/dev/null 2>&1
	repo sync -q -l --force-sync "$1"
	popd >/dev/null 2>&1
}

apply() {
	git -C "../$1"		am "$PWD/$1/$2"
}

pushd `dirname "$0"` >/dev/null 2>&1

reset	"frameworks/base"
reset	"system/core"
reset	"build/make"
reset	"bionic"
reset	"device/motorola/sanders"
reset	"kernel/motorola/msm8953"

apply	"frameworks/base"	"0001-Scroll-modified-velocitytracker.patch"
apply	"frameworks/base"	"0002-Frequently-used-OpenGL-ES-methods-whitelisted-for-fa.patch"
apply	"frameworks/base"	"0003-aapt-Default-to-0-compression-ratio.patch"
apply	"frameworks/base"	"0004-aapt-allow-opting-out-of-uncompressed-aapt.patch"
apply	"frameworks/base"	"0005-aapt-enforce-0-compression.patch"
apply	"frameworks/base"	"0006-frameworks-base-Fix-ContentService-JNI-leaks.patch"
apply	"frameworks/base"	"0007-core-jni-use-O3.patch"
apply	"frameworks/base"	"0008-DeadZone-add-missing-call-to-TypedArray.recycle.patch"
apply	"frameworks/base"	"0009-Optimize-AbsListView-to-reduce-click-operation-laten.patch"
apply   "frameworks/base"	"0010-Adding-optimization-to-reduce-callbacks-to-TextClock.patch"
apply   "frameworks/base"	"0011-media-fix-system_server-deadLock.patch"
apply   "frameworks/base"	"0012-Avoiding-NULL-pointer-dereferences.patch"
apply   "frameworks/base"	"0013-Optimize-set-bitmap-actions-in-RemoteViews.patch"

apply 	"system/core"		"0001-use-std-hash-instead-of-hashing-byte-by-byte.patch"
apply 	"system/core"		"0002-Enable-HAS_VFP_D32-for-32-bit-armv8-crasher.patch"
apply 	"system/core"		"0003-Silence-spammy-logs-from-camera-blobs-AEC_PORT-and-m.patch"
apply 	"system/core"		"0004-fix-null-pointer-and-memory-leak-issue.patch"
apply 	"system/core"		"0005-System-Server-Force-Close.patch"
apply	"system/core"		"0006-init-optimize-shutdown-time.patch"

apply	"build/make"		"0001-core-use-0-compression-when-creating-the-target_file.patch"
apply	"build/make"		"0002-Create-0-compression-ratio-jar-files.patch"
apply	"build/make"		"0003-Enable-GSS-garbage-collection.patch"
apply	"build/make"		"0004-zipalign-use-Zopfli-recompress-option.patch"

apply	"bionic"		"0001-Enable-32-bit-armv8-NEON-for-libm.patch"
apply   "bionic"                "0002-AArch64-Optimized-memcmp.patch"
apply   "bionic"                "0003-Optimize-the-clone-system-call-on-ARM-64.patch"
apply   "bionic"                "0004-Remove-an-obsolete-aarch64-hack.patch"
apply   "bionic"                "0005-libc-Optimize-ARM-memcmp-by-using-NEON.patch"
apply   "bionic"                "0006-libc-add-optimized-ARM64-strrchr-from-newlib.patch"
apply   "bionic"                "0007-libc-import-ARM-strcmp-from-newlib.patch"
apply   "bionic"                "0008-Find-clang-correctly.patch"
apply   "bionic"                "0009-bionic-strip-libc-and-linker.patch"
apply   "bionic"                "0010-AArch64-memcmp.S-optimize-for-medium-to-large-sizes.patch"
apply   "bionic"                "0011-AArch64-strcmp.S-Improve-performance-for-misaligned-.patch"
apply   "bionic"                "0012-aarch64-Improve-strncmp-for-mutually-misaligned-inpu.patch"
apply   "bionic"                "0013-aarch64-strncmp-Use-lsr-instead-of-mov-lsr.patch"
apply   "bionic"                "0014-libc-kryo-import-ARM-strlen-from-Apple-C-library.patch"
apply   "bionic"                "0015-libc-arm-Optimise-memchr-for-NEON-enabled-processors.patch"
apply   "bionic"                "0016-Use-builtins-for-fma-fmax-fmin-round-on-arm64.patch"
apply   "bionic"                "0017-Add-remaining-AArch32-and-ARM64-builtin-math-routine.patch"

apply	"device/motorola/sanders"	"0001-sanders-overlay-Enable-turbo-power-charger-support.patch"
apply	"device/motorola/sanders"	"0002-Set-up-EAS-on-device-boot.patch"
apply	"device/motorola/sanders"	"0003-sanders-Include-ARCore.patch"

apply	"kernel/motorola/msm8953"	"0001-drivers-thermal-queue-work-on-system_power_efficient.patch"
apply   "kernel/motorola/msm8953"	"0002-power-bcl-queue-work-on-system_power_efficient_wq.patch"
apply   "kernel/motorola/msm8953"	"0003-arm64-lib-memory-utilities-optimization.patch"
apply   "kernel/motorola/msm8953"	"0004-soc-qcom-secure_buffer-Fix-memory-leak.patch"
apply   "kernel/motorola/msm8953"	"0005-sdcardfs-fix-space-leak.patch"
apply   "kernel/motorola/msm8953"	"0006-clk-msm-clock-cpu-8953-Use-CLKFLAG_NO_RATE_CACHE-for.patch"
apply   "kernel/motorola/msm8953"	"0007-arm64-mmu-Fix-alloc_init_pud-section-mismatches.patch"
apply   "kernel/motorola/msm8953"	"0008-arm64-atomic-add-load-store-exclusive-functions.patch"
apply   "kernel/motorola/msm8953"	"0009-arm64-atomics-add-more-special-load-store.patch"
apply   "kernel/motorola/msm8953"	"0010-asm-generic-processor.h-adding-new-header-file.patch"
apply   "kernel/motorola/msm8953"	"0011-ARM64-defining-macros-to-optimize-power-usage.patch"
apply   "kernel/motorola/msm8953"	"0012-sched-Trying-to-reduce-power-usage.patch"
apply   "kernel/motorola/msm8953"	"0013-mutex-save-power-with-better-cpu_relax.patch"
apply   "kernel/motorola/msm8953"	"0014-asm-generic-atomic.h-relaxed-atomic_read.patch"
apply   "kernel/motorola/msm8953"	"0015-arm-atomic.h-defined-relaxed-atomic_read.patch"
apply   "kernel/motorola/msm8953"	"0016-arm64-atomic.h-defining-relaxed-atomic_read.patch"
apply   "kernel/motorola/msm8953"	"0017-asm-generic-relaxed.h-defined-relaxed.h.patch"
apply   "kernel/motorola/msm8953"	"0018-arm-asm-relaxed.h-defined-relaxed.h.patch"
apply   "kernel/motorola/msm8953"	"0019-asm-generic-processor.h-remove-redundant-macros.patch"
apply   "kernel/motorola/msm8953"	"0020-arm64-asm-relaxed.h-defined-relaxed.h.patch"
apply   "kernel/motorola/msm8953"	"0021-arm64-processor.h-remove-redundant-macros.patch"
apply   "kernel/motorola/msm8953"	"0022-hrtimer-enhance-power-efficiency.patch"
apply   "kernel/motorola/msm8953"	"0023-seqlock-enhance-power-efficiency.patch"
apply   "kernel/motorola/msm8953"	"0024-llist-defining-relaxed-version-of-llist_empty.patch"
apply   "kernel/motorola/msm8953"	"0025-smp-enhance-power-efficiency.patch"
apply	"kernel/motorola/msm8953"	"0026-llist-Replace-usages-of-llist_empty-with-relaxed-ver.patch"
apply	"kernel/motorola/msm8953"	"0027-hrtimer-Replace-usages-of-hrtimer_callback_running-w.patch"

popd >/dev/null 2>&1
