#!/usr/bin/env bash

reset() {
        echo -e "\e[33mResetting repo: $1\e[0m"
	pushd .. >/dev/null 2>&1
	repo sync -q -l --force-sync "$1"
	popd >/dev/null 2>&1
}

pushd `dirname "$0"` >/dev/null 2>&1

reset	"frameworks/base"
# reset	"system/core"
reset	"build/make"
reset	"bionic"
reset	"device/motorola/sanders"
reset	"kernel/motorola/msm8953"
reset	"frameworks/av"
reset	"frameworks/native"
reset	"art"

popd >/dev/null 2>&1
