#!/usr/bin/env bash

reset() {
        echo -e "\e[33mResetting repo: $1\e[0m"
	pushd ..
	repo sync -q -l --force-sync "$1"
}

pushd `dirname "$0"` >/dev/null 2>&1

reset	"frameworks/base"
reset	"system/core"
reset	"build/make"
reset	"bionic"

popd >/dev/null 2>&1
